version: '3'

volumes:
  data:

services:
  app: 
    container_name: 'api_pibic_malformacoes'
    build: .
    command: yarn dev
    ports: 
      - "3001:3001"
    volumes:
      - .:/usr/app
  database:
    environment:
      - MYSQL_ROOT_PASSWORD=root 
      - TZ=America/Sao_Paulo
    container_name: 'database-api-pibic-malformacoes'
    image: mysql:5.7.31
    restart: always
    ports:
      - "3307:3306"
    volumes:
      - data:/var/lib/mysql
